# Etape 1 : Compilation
FROM maven:3.9.6-eclipse-temurin-17 AS builder
WORKDIR /app
COPY bookshop/pom.xml .
RUN mvn dependency:go-offline -B
COPY bookshop/src ./src
RUN mvn package -DskipTests -B

# Etape 2 : Image finale
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]